#!/bin/bash -l

#PBS -N compute_A
#PBS -A URIC0009
#PBS -q main
#PBS -l select=1:ncpus=1:mpiprocs=1:ompthreads=1:mem=4GB
#PBS -l walltime=01:00:00
#PBS -j oe 
###PBS -o job-logs/compute_A_${PBS_JOBID}.out
###PBS -e job-logs/compute_A_${PBS_JOBID}.err
#PBS -m abe

source /glade/u/home/kjakhar/.bashrc
# module load conda
conda activate evt
# python -u -m test.py

python3 -u -m compute_truth.py ${var} ${sim_number} ${reduce} ${lat} ${lon}
