#!/bin/bash -l

#PBS -N compute_A
#PBS -A URIC0009
#PBS -q main 
#PBS -l select=1:ncpus=1:mpiprocs=1:ompthreads=1
#PBS -l walltime=03:00:00
#PBS -j oe 
#PBS -m abe


source /glade/u/home/kjakhar/.bashrc
conda activate evt
# python -u -m test.py

python3 -u -m compute_A_train.py ${var} ${sim_number} ${reduce} ${lat} ${lon}

# python3 -u -m compute_A_train.py ${var} ${sim_number} ${reduce} ${lat} ${lon} &
# wait